# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uakdPC3F94jobL_jdr1ORZyGZlB5Qr6P
"""

# Initial values
a = 5
b = 10

# Swapping using a temporary variable
temp = a
a = b
b = temp

print("After swapping: a =", a, ", b =", b)